# Cloudflare Worker wrangler.toml
name = "remote-mcp-server-authless"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Development configuration
[dev]
port = 8787

# Production configuration
[env.production]
workers_dev = false
route = "mcp.s-imsy.com/*"

# Environment variables
[vars]
TOKEN = "your-secret-token-here"  # Replace with your actual token 